- id: doi:10.1101/2021.05.03.442423 
  image: ../images/publications/fong-duffy2021_thumbnail.svg
  date: '2021-05-04'
  publisher: bioRxiv


- id: doi:10.1523/JNEUROSCI.1393-19.2020 
  image: ../images/publications/hanes2020_jneuro_thumbnail.svg


- id: doi:10.1093/cercor/bhz260
  image: ../images/publications/fong2020-cerebctx_thumbnail.svg
  authors:
  - Ming-fai Fong
  - Peter S.B. Finnie
  - Taekeun Kim
  - Aurore Thomazeau
  - Eitan S. Kaplan
  - Samuel F. Cooke
  - Mark F. Bear


- id: doi:10.1002/cne.24336
  image: ../images/publications/duffy2018-jcn_thumbnail.svg


- id: doi:10.1073/pnas.1613279113
  image: ../images/publications/fong2016-pnas_thumbnail.svg


- id: doi:10.7554/eLife.07192
  image: ../images/publications/newman2016-elife_thumbnail.svg


- id: doi:10.1038/ncomms7339
  image: ../images/publications/fong2016-natcomm_thumbnail.svg


- id: doi:10.3389/fncir.2013.00184
  image: ../images/publications/tchumatchenko-newman2013-frontiers_thumbnail.svg


- id: doi:10.3389/fncir.2012.00098
  image: ../images/publications/newman2013-frontiers_thumbnail.svg


- id: doi:10.1109/ROBOT.2004.1302452
  image: ../images/publications/tedrake2004-icra_thumbnail.svg
  publisher: IEEE International Conference on Robotics and Automation
